---
- name: Instalamos WP-CLI.
  get_url:
    url: "{{ wp_cli_url }}"
    dest: "{{ wp_cli_path }}"
    force: true
    owner: "{{ wp_cli_webserver_user }}"
    group: "{{ wp_cli_webserver_group }}"
    mode: 0755

- name: Instalamos los plugins de WP-CLI.
  command: "{{ wp_cli_bin }} package install {{ item }}"
  register: resultado
  changed_when: "'Installing package' in resultado.stdout"
  when: item is defined
  with_items:
    - "{{ wp_cli_packages }}"

- name: Comprobamos si existe el archivo de WordPress readme.html
  stat:
    path: "{{ item.path }}/readme.html"
  register: wp_readme_{{ item }}
  with_items:
    - "{{ wp_cli_sites }}"

- name: Descargamos WordPress.
  command: "{{ wp_cli_bin }} core download --locale='{{ item.locale }}' --path='{{ item.path }}' --version='{{ item.version }}'"
  args:
    creates: "{{ item.path }}/wp-settings.php"
  become: yes
  become_user: "{{ wp_cli_webserver_user }}"
  with_items:
    - "{{ wp_cli_sites }}"

- name: Configuramos WordPress.
  command: "{{ wp_cli_bin }} core config --path='{{ item.path }}' --dbname='{{ item.db }}' --dbuser='{{ item.db_user }}' --dbpass='{{ item.db_pass }}' --dbhost='{{ item.db_host }}' --dbprefix='{{ item.dp_prefix }}'"
  args:
    creates: "{{ item.path }}/wp-config.php"
  become: yes
  become_user: "{{ wp_cli_webserver_user }}"
  with_items:
    - "{{ wp_cli_sites }}"

- name: Instalamos WordPress.
  command: "{{ wp_cli_bin }} core install --path='{{item.path }}' --url='{{ item.url }}' --title='{{ item.title }}' --admin_user='{{ item.admin_user }}' --admin_password='{{ item.admin_password }}' --admin_email='{{ item.admin_email }}' --skip-email"
  become: yes
  become_user: "{{ wp_cli_webserver_user }}"
  when: wp_readme_{{ item }}.stat.exists == True
  with_items:
    - "{{ wp_cli_sites }}"

- name: Permisos de carpetas y archivos en WordPress (Folders 755, Files 644).
  file:
    path: "{{ item.path }}"
    mode: u=rwX,g=rX,o=rX
    owner: "{{ wp_cli_webserver_user }}"
    group: "{{ wp_cli_webserver_group }}"
    recurse: yes
  with_items:
    - "{{ wp_cli_sites }}"

- name: Eliminamos licencia.txt del raiz de WordPress.
  file:
    path: "{{ item.path }}/licencia.txt"
    state: absent
  with_items:
    - "{{ wp_cli_sites }}"

- name: Eliminamos license.txt del raiz de WordPress.
  file:
    path: "{{ item.path }}/license.txt"
    state: absent
  with_items:
    - "{{ wp_cli_sites }}"

- name: Eliminamos readme.html del raiz de WordPress.
  file:
    path: "{{ item.path }}/readme.html"
    state: absent
  with_items:
    - "{{ wp_cli_sites }}"